language: objective-c
osx_image: xcode8
env:
  - DESTINATION="OS=10.0,name=iPhone 6s" SCHEME="JTAppleCalendar-Example" SDK=iphonesimulator10.0 CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace Example/JTAppleCalendar.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
 notifications:
  email: false
